export const OPERATION_TO_PERFORM = {
  ADD_BACKGROUND: "ADD_BACKGROUND",
  REMOVE_BACKGROUND: "REMOVE_BACKGROUND",
  ENHANCE_IMAGE: "ENHANCE_IMAGE",
};

export const BASE_URL =
  import.meta.env.VITE_BASE_URL || "http://localhost:3000";
